"""Fleet: this device's enrollment, from the fleet agent itself.

`shani-fleet-agent status` prints "key: value" lines and is shown as they are.
Enrollment is also here, because the page already holds the one thing that can
perform it and the token is a single short-lived secret: the agent's own
`enroll` needs the organisation's token and nothing else.

**Why this used to be read-only, and what changed.** The page reported that
enrollment is "done by the organisation" and named no way to do it, which is
true of the *token* - an organisation issues those, and only an organisation
administrator can issue one - and was being read as "this machine cannot be
enrolled from its own desktop". The agent has supported `enroll` since it
existed; nothing in Cassini drove it.

**The one honest limit, stated on the row rather than hidden.** A device key is
generated and returned by the fleet *server* when it accepts a token, so
enrolling needs an organisation that exists. This page cannot create one. The
button therefore appears whether or not the machine is enrolled, and its own
subtitle says what a token is and where it comes from, rather than the page
pretending to be a self-service portal.

**The token never reaches argv.** `cmd_enroll` does `read -rp "Enrollment token: "`,
which is bash reading a line from stdin - there is no flag that takes a token as
an argument. `run_streaming_stdin()` answers that prompt on the child's stdin,
so the secret is never in `/proc/<pid>/cmdline`, and it is written to a pipe
rather than to a terminal, so it is not echoed either. Nothing on this page
logs the answer, and the entry row is cleared as soon as the dialog closes.

**A second `enroll` is refused by the agent, not by this page.** Re-enrolling
overwrites a machine identity and orphans the record the server holds, which is
why `cmd_enroll` dies without `--force`. The page reads the real `enrolled:`
line out of `status` and offers "Enroll again…" only when it says the machine
*is* enrolled, with the consequence in the confirmation - so the page's wording
and the tool's refusal cannot drift into disagreeing.
"""

from __future__ import annotations

import logging

from gi.repository import Adw, GLib, Gtk  # type: ignore

from shani_cassini import system_status as ss

logger = logging.getLogger(__name__)
AGENT = "shani-fleet-agent"

ENROLL = "enroll"
UNENROLL = "uninstall"

ENROLL_BODY = (
    "This registers the device with your organisation: it will appear in that "
    "organisation's inventory, and receive its signed update and rollback "
    "commands.\n\n"
    "You need an enrollment token from whoever administers that organisation. "
    "The device key is generated by the server when it accepts the token, so a "
    "device cannot enroll itself without one."
)
REENROLL_BODY = (
    "This machine is already enrolled. Enrolling again replaces its identity, "
    "and the record the organisation holds for the old one goes stale - it stays "
    "listed but reports nothing.\n\n"
    "Only do this if you are deliberately re-enrolling this device as a new "
    "machine."
)
UNENROLL_BODY = (
    "This stops and disables the fleet systemd units on this machine and "
    "deletes its local fleet state.\n\n"
    "It does not remove the machine from your organisation's console - that "
    "stays listed with its last known state until an administrator removes it. "
    "Nothing is deployed or changed by this."
)


def _esc(value: object) -> str:
    """Every string that came off the command's output, escaped.

    A subtitle and a title are both parsed as markup by libadwaita, and the
    agent's output includes a URL and a machine id, neither of which Cassini
    controls. An unescaped '&' is not a slightly wrong font - the parse fails
    and the row renders as nothing at all.
    """
    return GLib.markup_escape_text(str(value), -1)


# The agent's own wording, so a dismissed dialog is not reported as a failure
# and a missing binary is not reported as a policy decision.
CANCELLED: str = "Authorization was cancelled"
NOT_INSTALLED: str = "This device's fleet agent is not installed"


def _looks_unenrolled(value: str) -> bool:
    """Whether a `status` line says this machine is not enrolled.

    The agent's line is `enrolled: no (run: shani-fleet-agent enroll)`, and its
    `status` output is plain text, not a contract with a version field - so the
    one fact needed here is read out of the value rather than from a key that
    might not be the one this version prints.

    Anything unrecognised reads as *not* saying no. The consequence is the safe
    one: the page then offers plain "Enroll…", and the agent itself refuses a
    second enrollment without --force.
    """
    return value.strip().lower().startswith("no")


def _machine_id(value: str) -> str:
    """The machine id out of `enrolled: yes (machine_id=m-abc)`, if present."""
    marker = "machine_id="
    if marker not in value:
        return ""
    return value.split(marker, 1)[1].rstrip(")").strip()


class FleetTab(Gtk.Box):
    def __init__(self, state=None, auth_manager=None) -> None:
        super().__init__(orientation=Gtk.Orientation.VERTICAL, spacing=24)
        self._state = state
        self._auth_manager = auth_manager
        self._toasts = Adw.ToastOverlay()
        self.append(self._toasts)
        page = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=24)
        self._toasts.set_child(page)

        self._enrolled: bool | None = None
        self._machine_id = ""
        self._busy = False
        # The dialog currently on screen, if any. Kept so it can be closed, and
        # so a test can reach it without a window - see _present().
        self._dialog: Adw.AlertDialog | None = None
        # The agent's own status output, kept so the enrollment state can be
        # re-derived from it without a second privileged call. Parsed on the way
        # in rather than kept as a widget: a *view* of the tool's output that
        # outlived the run that produced it would keep asserting facts about a
        # machine whose state has since changed.
        self._enrolled_line = ""

        self._membership = Adw.PreferencesGroup(
            title="This device",
            description="An enrolled device reports its inventory and health to "
                        "your organisation and runs the signed commands it sends.")
        row = Adw.ActionRow(title="Agent status", subtitle="Reading it needs your password")
        self._btn = Gtk.Button(label="Show", valign=Gtk.Align.CENTER)
        self._btn.connect("clicked", lambda *_: self._load())
        row.add_suffix(self._btn)
        self._membership.add(row)

        self._row_identity = Adw.ActionRow(title="Enrollment", subtitle="Not read yet")
        self._row_identity.set_subtitle_selectable(True)
        self._btn_enroll = Gtk.Button(label="Enroll…", valign=Gtk.Align.CENTER)
        self._btn_enroll.add_css_class("suggested-action")
        self._btn_enroll.connect("clicked", lambda *_: self._enroll_dialog(False))
        self._row_identity.add_suffix(self._btn_enroll)

        self._btn_unenroll = Gtk.Button(label="Remove…", valign=Gtk.Align.CENTER)
        self._btn_unenroll.add_css_class("destructive-action")
        self._btn_unenroll.set_tooltip_text(
            "Removes this device's local fleet identity. It does not remove it "
            "from your organisation's console - an administrator does that.")
        self._btn_unenroll.connect("clicked", lambda *_: self._unenroll_dialog())
        # Enroll and unenroll sit either side of a separator rather than
        # adjacent: they are opposite actions on the same state, and a
        # destructive button one thumb-width from its own inverse invites the
        # wrong one. Found by rendering the page - two similarly-sized buttons,
        # one of them styled as destructive, is not a safe pairing.
        sep = Gtk.Separator(orientation=Gtk.Orientation.VERTICAL,
                            valign=Gtk.Align.CENTER)
        self._row_identity.add_suffix(sep)
        self._row_identity.add_suffix(self._btn_unenroll)
        self._membership.add(self._row_identity)
        page.append(self._membership)

        self._status = Adw.PreferencesGroup(title="Status", visible=False)
        page.append(self._status)
        self._render_membership()

    # ----------------------------------------------------------------- status
    def _present(self, dialog: Adw.AlertDialog) -> None:
        """Show a dialog, and keep a handle so it can be reached without a window.

        Two reasons this is not a bare `dialog.present(self.get_root())`. The
        handle is what makes the dialog testable at all: `get_root()` is None
        until the page is in a window, so a test that walks the widget tree for
        an Adw.AlertDialog finds nothing while the code looks fine - which is
        how this repo has been fooled before. And the second dialog opened while
        one is up should replace it rather than stack a second copy of the same
        prompt on screen.
        """
        if self._dialog is not None:
            self._dialog.close()
        self._dialog = dialog
        dialog.present(self.get_root())

    def _load(self) -> None:
        if self._busy:
            return
        self._busy = True
        self._btn.set_sensitive(False)
        lines: list[str] = []

        def done(rc):
            self._busy = False
            self._btn.set_sensitive(True)
            if rc in (126, 127):
                self._toasts.add_toast(Adw.Toast(title=CANCELLED))
                return
            self._show(lines, rc)

        ss.run_streaming(["pkexec", AGENT, "status"], lines.append, done)

    def _clear_status(self) -> None:
        """Take the whole output group down, rather than emptying it.

        The group is rebuilt from scratch on every read, so emptying it in place
        would be work for nothing; and a group left visible but empty is a blank
        box under a "Status" heading, which reads as a tool that said nothing
        rather than as one that was not asked.
        """
        parent = self._status.get_parent()
        if parent is not None:
            parent.remove(self._status)
        self._status = Adw.PreferencesGroup(title="Status", visible=False)
        parent = self._status.get_parent()
        if parent is not None:
            parent.append(self._status)

    def _show(self, lines: list[str], rc: int) -> None:
        parent = self._status.get_parent()
        new = Adw.PreferencesGroup(title="Status")
        for line in lines:
            if ": " not in line:
                if line.strip():
                    new.set_description(_esc(line.strip()))  # the version line
                continue
            key, val = line.split(": ", 1)
            value = val.strip()
            # The one line this page acts on rather than merely shows.
            if key.strip().lower() == "enrolled":
                self._enrolled_line = value
                self._enrolled = not _looks_unenrolled(value)
                self._machine_id = _machine_id(value)
            bad = any(w in value for w in ("NO", "NOT", "never", "fail"))
            row = Adw.ActionRow(title=_esc(key.strip().capitalize()),
                                subtitle=_esc(value))
            row.set_subtitle_selectable(True)
            if bad:
                img = Gtk.Image.new_from_icon_name("dialog-warning-symbolic")
                img.add_css_class("warning")
                row.add_prefix(img)
            new.add(row)
        if rc != 0 and not lines:
            new.set_description("The agent did not answer")
        parent.remove(self._status)
        parent.append(new)
        self._status = new
        self._render_membership()

    # ------------------------------------------------------------- membership
    def _render_membership(self) -> None:
        """The enrollment row, from the last status read or from its absence.

        Three states, and the third is the one a first visit is in: nothing has
        been read, so the page says so rather than asserting a membership it has
        not established. The buttons are gated on the *reading*, not on the
        guess - `enroll` is offered either way, because a machine with no
        reading may well be enrolled and the agent will refuse it if so.
        """
        if self._enrolled is None:
            subtitle = ("Not read yet - press Show to see whether this device "
                        "is enrolled")
            label = "Enroll…"
            can_enroll = True
            can_unenroll = False
            self._btn_unenroll.set_visible(False)
        elif self._enrolled:
            ident = f" as {_esc(self._machine_id)}" if self._machine_id else ""
            subtitle = f"Enrolled{ident}"
            label = "Enroll again…"
            can_enroll = True
            can_unenroll = True
            self._btn_unenroll.set_visible(True)
        else:
            subtitle = ("Not enrolled - this device is not reported to any "
                        "organisation")
            label = "Enroll…"
            can_enroll = True
            can_unenroll = False
            self._btn_unenroll.set_visible(False)
        self._row_identity.set_subtitle(subtitle)
        self._btn_enroll.set_label(label)
        self._btn_enroll.set_sensitive(can_enroll and not self._busy)
        self._btn_unenroll.set_sensitive(can_unenroll and not self._busy)

    # --------------------------------------------------------------- actions
    def _enroll_dialog(self, force: bool) -> None:
        if force or self._enrolled:
            body = REENROLL_BODY if force else ENROLL_BODY
        else:
            body = ENROLL_BODY
        dialog = Adw.AlertDialog(
            heading="Enroll this device" if not force else "Enroll this device again",
            body=body)
        group = Adw.PreferencesGroup()
        token = Adw.PasswordEntryRow(title="Enrollment token")
        group.add(token)
        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=12)
        box.append(group)
        dialog.set_extra_child(box)
        dialog.add_response("cancel", "Cancel")
        dialog.add_response("enroll", "Enroll")
        dialog.set_response_appearance("enroll", Adw.ResponseAppearance.SUGGESTED)
        dialog.set_default_response("enroll")
        dialog.set_close_response("cancel")

        def check(*_args):
            dialog.set_response_enabled("enroll", bool(token.get_text()))
        token.connect("changed", check)
        check()

        def responded(_d, response):
            secret = token.get_text()
            token.set_text("")  # gone before anything is spawned
            if response != "enroll" or not secret:
                return
            argv = ["pkexec", AGENT, ENROLL] + (["--force"] if force else [])
            # The token is a line on stdin; the agent's own `read -rp` takes it.
            self._run_with_stdin(argv, secret + "\n", "Enrolling this device…")

        dialog.connect("response", responded)
        self._present(dialog)

    def _unenroll_dialog(self) -> None:
        dialog = Adw.AlertDialog(heading="Remove this device from the fleet?",
                                 body=UNENROLL_BODY)
        dialog.add_response("cancel", "Cancel")
        dialog.add_response("unenroll", "Remove")
        dialog.set_response_appearance("unenroll", Adw.ResponseAppearance.DESTRUCTIVE)
        dialog.set_default_response("cancel")
        dialog.set_close_response("cancel")

        def responded(_d, response):
            if response != "unenroll":
                return
            # `--yes`, not a "y" written to the prompt. cmd_uninstall answers its
            # own "Continue? [y/N]" and then `return 0`s when the answer is
            # anything else - so a declined confirmation exits **0**, identical
            # to a completed one, and the exit status could not tell the user
            # whether their device was removed. The flag skips the prompt, which
            # is the only way to make the status mean what it says. This page
            # asked first, in the dialog above.
            self._run(["pkexec", AGENT, "uninstall", "--yes"],
                      "Removing this device from the fleet…")

        dialog.connect("response", responded)
        self._present(dialog)

    def _begin(self, what: str) -> None:
        """Grey out every action for the length of a call, and say it is running.

        Busy state is a latch, not a timer: a user who clicks twice must not
        start two enrollments, and nothing here decides when the call is over -
        only the tool's exit does.
        """
        self._busy = True
        self._btn.set_sensitive(False)
        self._render_membership()
        toast = Adw.Toast.new(what)
        toast.set_timeout(2)
        self._toasts.add_toast(toast)

    def _run_with_stdin(self, argv, secret: str, what: str) -> None:
        """Run a prompting tool, answering it on stdin, and report the outcome.

        The tool's own output is logged at debug and never rendered: `enroll`
        echoes back what it read, and putting a stream that contains a secret
        into a widget is the one way this dialog could leak the token after the
        entry row was cleared.
        """
        self._run(argv, what, stdin=secret)

    def _run(self, argv, what: str, stdin: str | None = None) -> None:
        """One fleet agent call: latch busy, run it, report how it ended.

        `_begin` is called from *here* rather than from each caller. It was the
        other way round first, and the unenroll path - which has no secret to
        write - never got it: the page stayed clickable for the whole removal
        and `_busy` never went true, so "wait for it to finish" had nothing to
        wait on. A latch that only some callers set is a latch that does not
        hold.

        The two runners are called through their own branches rather than picked
        as a callable: their signatures differ by the stdin argument, so a single
        `runner(argv, stdin or "", ...)` passes a phantom argument to the one
        with no stdin - a TypeError inside a GTK callback, which GLib swallows
        into a button that silently did nothing.
        """
        self._begin(what)

        def line(text: str) -> None:
            # Debug only, and never into a widget: `enroll` echoes back what it
            # read, and a pane is not a place a secret survives in.
            logger.debug("fleet agent said: %s", text)

        def exited(rc: int) -> None:
            self._busy = False
            self._btn.set_sensitive(True)
            if rc in (126, 127):
                # pkexec's own codes: the dialog was dismissed. Not a failure
                # of the agent, and not worth the word "failed".
                self._toasts.add_toast(Adw.Toast(title=CANCELLED))
            elif rc == 0:
                # Everything on screen here was read from a state the agent has
                # just changed, so all of it goes - not just the membership
                # row. Leaving the raw output group up would keep asserting
                # `enrolled: yes (machine_id=m-old)` after the machine has been
                # re-enrolled as something else, which is the app reporting a
                # fact it knows to be stale.
                self._enrolled = None
                self._machine_id = ""
                self._enrolled_line = ""
                self._clear_status()
                self._toasts.add_toast(Adw.Toast(
                    title="Done - press Show to read the result"))
            else:
                # The agent's reason went to its log, not to a widget: it is the
                # one stream that may carry the token back.
                self._toasts.add_toast(Adw.Toast(
                    title="It did not complete - the fleet log has the reason"))
            self._render_membership()

        if stdin is not None:
            ss.run_streaming_stdin(argv, stdin, line, exited)
        else:
            ss.run_streaming(argv, line, exited)
